<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
    <SignAssembly>False</SignAssembly>
	  <Authors>Łukasz Górski</Authors>
	  <Copyright>Copyright © 2023-2026 Łukasz Górski</Copyright>
	  <RepositoryUrl>https://github.com/lukegor/PriceNegotiationApp</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="SonarAnalyzer.CSharp">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="StyleCop.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="xunit.runner.visualstudio">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="coverlet.collector">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Application\Negotiations\" />
    <Folder Include="Application\Products\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\PriceNegotiationApp.Api\PriceNegotiationApp.Api.csproj" />
  </ItemGroup>

</Project>
