// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PriceNegotiationApp.Modules.Negotiations.Persistence;

#nullable disable

namespace PriceNegotiationApp.Modules.Negotiations.Persistence.Migrations
{
    [DbContext(typeof(NegotiationsDbContext))]
    [Migration("20260825131537_SnapshotPolicyLimitsAndWithdrawn")]
    partial class SnapshotPolicyLimitsAndWithdrawn
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("negotiations")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PriceNegotiationApp.Modules.Negotiations.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("IdentityUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("identity_user_id");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("IdentityUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_customers_identity_user_id");

                    b.ToTable("customers", "negotiations");
                });

            modelBuilder.Entity("PriceNegotiationApp.Modules.Negotiations.Domain.Negotiation", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("base_price");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<decimal>("CurrentOffer")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_offer");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset?>("DecidedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("decided_at_utc");

                    b.Property<DateTimeOffset>("LastProposalAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_proposal_at_utc");

                    b.Property<DateTimeOffset?>("LastStaffActionAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_staff_action_at_utc");

                    b.Property<int>("MaxProposals")
                        .HasColumnType("integer")
                        .HasColumnName("max_proposals");

                    b.Property<decimal>("OfferMultiplierLimit")
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("offer_multiplier_limit");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<int>("ProposalsUsed")
                        .HasColumnType("integer")
                        .HasColumnName("proposals_used");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<uint>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("xid")
                        .HasColumnName("xmin");

                    b.HasKey("Id")
                        .HasName("pk_negotiations");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_negotiations_customer_id");

                    b.HasIndex("ProductId", "CustomerId")
                        .IsUnique()
                        .HasDatabaseName("uq_negotiations_open_product_customer")
                        .HasFilter("status = 1");

                    b.ToTable("negotiations", "negotiations");
                });

            modelBuilder.Entity("PriceNegotiationApp.Modules.Negotiations.Domain.Negotiation", b =>
                {
                    b.HasOne("PriceNegotiationApp.Modules.Negotiations.Domain.Customer", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_negotiations_customers_customer_id");
                });
#pragma warning restore 612, 618
        }
    }
}
