<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <NoWarn>$(NoWarn);MA0182</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\PriceNegotiationApp.Modules.Catalog.Domain\PriceNegotiationApp.Modules.Catalog.Domain.csproj" />
    <ProjectReference Include="..\PriceNegotiationApp.Modules.Catalog.Contracts\PriceNegotiationApp.Modules.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\..\..\PriceNegotiationApp.SharedKernel\PriceNegotiationApp.SharedKernel.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PriceNegotiationApp.Modules.Catalog.Infrastructure" />
    <InternalsVisibleTo Include="PriceNegotiationApp.Modules.Catalog.Tests" />
    <InternalsVisibleTo Include="PriceNegotiationApp.ArchitectureTests" />
    <InternalsVisibleTo Include="PriceNegotiationApp.Api" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
  </ItemGroup>
</Project>
