<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Catalog\PriceNegotiationApp.Modules.Catalog.Application\PriceNegotiationApp.Modules.Catalog.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\PriceNegotiationApp.Modules.Catalog.Infrastructure\PriceNegotiationApp.Modules.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Catalog\PriceNegotiationApp.Modules.Catalog.Contracts\PriceNegotiationApp.Modules.Catalog.Contracts.csproj" />
    <ProjectReference Include="..\PriceNegotiationApp.TestKit\PriceNegotiationApp.TestKit.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Bogus" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
