<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\..\src\Modules\Negotiations\PriceNegotiationApp.Modules.Negotiations.Application\PriceNegotiationApp.Modules.Negotiations.Application.csproj" />
    <ProjectReference Include="..\..\src\Modules\Negotiations\PriceNegotiationApp.Modules.Negotiations.Infrastructure\PriceNegotiationApp.Modules.Negotiations.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Modules\Negotiations\PriceNegotiationApp.Modules.Negotiations.Contracts\PriceNegotiationApp.Modules.Negotiations.Contracts.csproj" />
    <ProjectReference Include="..\..\src\PriceNegotiationApp.SharedKernel\PriceNegotiationApp.SharedKernel.csproj" />
    <ProjectReference Include="..\PriceNegotiationApp.TestKit\PriceNegotiationApp.TestKit.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Bogus" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="Microsoft.Testing.Extensions.TrxReport" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>
</Project>
